name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repository metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MONCHOBRONCHO
          repo: UnityX
          template: classic
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          committer_gist: ${{ secrets.METRICS_TOKEN }}
          plugin_lines: yes
